.\" Process this file with
.\" groff -man -Tascii gstyle.1
.\"
.TH GSTYLE 1 "JUNE 2010" Linux "User Manuals"
.SH NAME
GSTYLE \- Customise your gnome desktop and more
.SH SYNOPSIS
.B Gstyle [
.I OPTIONS
.B ]
.SH DESCRIPTION
.B Gstyle
is an open source software for gnome
.SH BUGS
Please report all bugs to the gstyle team:
https://bugs.launchpad.net/ubukey

Copyright 2009-2010. Licensed under GPL, version 2 or higher version.